backend:
  name: github
  repo: wpmetabox/docs
  branch: master

media_folder: "assets/images"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Post" # Used in the UI, e.g., "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "foo"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
